# Generated by Django 2.0.7 on 2018-08-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('food', models.CharField(max_length=64)),
                ('menu', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=1)),
                ('price', models.FloatField()),
                ('processed', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(),
        ),
    ]
