# Generated by Django 2.0.7 on 2018-08-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180801_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='topping1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='topping2',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='topping3',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
