# Generated by Django 2.0.7 on 2018-08-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180801_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='ordered',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
